import Head from 'next/head'
import favicon from "../../public/favicon.ico"
import Header from './header'
import BoostYourLink from './BoostYourLink'
import Statistics from './Statistics'
import InputSection from './Input'

const Home = () => (
    <div>
      <Head>
        <title>MINDMOVER Task</title>
        <meta name="description" content="Generated by MINDMOVER Task" />
        <link rel="icon" href={favicon} />
      </Head>
      <Header />
      <div style={{ backgroundColor: '#EFF1F7' }}>
      <InputSection />
      <Statistics />
      <BoostYourLink />
      </div>
    </div>
  )

export default Home